---
title: The Master's University
timezone: UTC
collections:
  faculty:
    title: Faculty
    output: true
  gradprograms:
    title: Grad Programs
    output: true
  landingPageBanners:
    title: Landing Page Banners
    output: false
  onlineprograms:
    title: Online Programs
    output: true
  posts:
    title: Posts
    output: true
  departments:
    title: Undergrad Majors
    output: true
  upcomingevents:
    title: Upcoming Events
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: landingPageBanners
  values:
    description: ''
    image: ''
    link: ''
    title: ''
    button-text: ''
- scope:
    path: ''
    type: upcomingevents
  values:
    title: ''
    image: ''
    event_date: ''
    description: ''
- scope:
    path: ''
    type: posts
  values:
    layout: news
    title: ''
    permalink: "/news/:title"
- scope:
    path: ''
    type: departments
  values:
    layout: undergradmajor
    title: ''
    description: ''
    permalink: "/academics/undergraduate/:title"
- scope:
    path: ''
    type: gradprograms
  values:
    layout: gradprogram
    title: ''
    permalink: "/academics/graduate/:title"
- scope:
    path: ''
    type: onlineprograms
  values:
    layout: onlineprogram
    title: ''
    permalink: "/academics/online/:title"
- scope:
    path: ''
    type: faculty
  values:
    layout: faculty
    title: ''
    permalink: faculty/:title
    job-title: ''
    image: ''
    description: ''
    undergrad majors: ''
    degrees:
    -
    -
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url: https://blakenoll.github.io/TMU/
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme:
sass:
  style: compressed
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
